NumPy Retail Analytics Assignment

Business Scenario

You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

sales_data — monthly sales revenue generated by each store for different product categories.

cost_data — total cost incurred by each store for the same product categories.

In [2]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

Question 1: Array Dimensions

The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data

Shape of sales_data

Total number of values

Data type of the array

Memory occupied by the array

In [ ]:
print(sales_data.ndim)
print(sales_data.shape)
print(sales_data.size)
print(sales_data.dtype)
print(sales_data.nbytes)

2
(5, 6)
30
int64
240


Question 2: Store and Category Count

Calculate the following:

Total number of stores

Total number of product categories

Total number of store-category combinations

In [ ]:
print(stores.size)       # total number of stores
print(categories.size)        # number of product categories
print(sales_data.shape[0] * sales_data.shape[1])        # shape[0] gives number of rows in stores, shape[1] gives number of columns in product categories

5
6
30


Question 3: Sales Data Type Conversion

The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32

float64

Compare the memory used by both arrays.

In [ ]:
print(sales_data.astype(np.float32).nbytes)
print(sales_data.astype(np.float64).nbytes)          # float64 uses double the memory of float32

120
240


Part 3: Indexing and Data Extraction

Question 4: Bengaluru Store Analysis

The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [ ]:
print(sales_data[0])           # complete sales row for bengaluru

[850000 420000 310000 275000 190000 225000]


Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

In [ ]:
print(cost_data[3])       # total cost incurred by mumbai stores for all product categories

[790000 390000 265000 250000 165000 205000]


Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

In [ ]:
print(sales_data[:,0])

[ 850000  780000  920000 1050000  690000]


Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from cost_data.

In [ ]:
print(cost_data[:,2])     # clothing cost from all stores

[220000 210000 245000 265000 205000]


Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

Furniture sales

Furniture cost

Furniture profit

In [ ]:
print(sales_data[1, 3])
print(cost_data[1, 3])
print(sales_data[1, 3] - cost_data[1, 3])

310000
225000
85000


Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

Groceries

Clothing

Furniture

Use array slicing.

In [ ]:
print(sales_data[2, 1:2])     # it gives chennai groceries sales
print(sales_data[2,2:3])      # it gives chennai clothing sales
print(sales_data[2,3:4])     # it gives chennai furniture sales

[390000]
[340000]
[260000]


Question 10: Selected Store Analysis

Extract sales data for:

Bengaluru

Chennai

Pune

Include only:

Electronics

Clothing

Beauty

Use advanced indexing.

In [ ]:
print(sales_data[[0, 2, 4]][:,[0, 2, 4]])

[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


Part 4: Sales Aggregation

Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

In [ ]:
print(sales_data.sum())

11675000


Question 12: Store-Wise Sales

Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

Bengaluru: total sales

Hyderabad: total sales

Chennai: total sales

Mumbai: total sales

Pune: total sales

In [ ]:
print("Bengaluru : ",np.sum(sales_data[0]))
print("Hyderabad : ",np.sum(sales_data[1]))
print("Chennai :", np.sum(sales_data[2]))
print("Mumbai : ",np.sum(sales_data[3]))
print("Pune : ",np.sum(sales_data[4]))

Bengaluru :  2270000
Hyderabad :  2295000
Chennai : 2310000
Mumbai :  2820000
Pune :  1980000


Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [ ]:
print("Electronics :",np.sum(sales_data[:,0]))
print("Groceries:",np.sum(sales_data[:,1]))
print("Clothing sales:",np.sum(sales_data[:,2]))
print("Furniture sales:",np.sum(sales_data[:,3]))
print("Beauty sales:",np.sum(sales_data[:,4]))
print("Sports sales:",np.sum(sales_data[:,5]))

Electronics : 4290000
Groceries: 2185000
Clothing sales: 1600000
Furniture sales: 1415000
Beauty sales: 1010000
Sports sales: 1175000


Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

In [ ]:
print("Average sales of bengaluru store:",np.average(sales_data[0], axis = 0))
print("Average sales of hyderabad store:",np.average(sales_data[1], axis = 0))
print("Average sales of chennai store:",np.average(sales_data[2], axis = 0))
print("Average sales of mumbai store:",np.average(sales_data[3], axis = 0))
print("Average sales of pune store:",np.average(sales_data[4], axis = 0))

Average sales of bengaluru store: 378333.3333333333
Average sales of hyderabad store: 382500.0
Average sales of chennai store: 385000.0
Average sales of mumbai store: 470000.0
Average sales of pune store: 330000.0


Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

In [ ]:
print("Average sales of electronics category:", np.average(sales_data[:,0]))
print("Average sales of groceries category:", np.average(sales_data[:,1]))
print("Average sales of clothing category:", np.average(sales_data[:,2]))
print("Average sales of furniture category:", np.average(sales_data[:,3]))
print("Average sales of beauty category:", np.average(sales_data[:,4]))
print("Average sales of sports category:", np.average(sales_data[:,5]))

Average sales of electronics category: 858000.0
Average sales of groceries category: 437000.0
Average sales of clothing category: 320000.0
Average sales of furniture category: 283000.0
Average sales of beauty category: 202000.0
Average sales of sports category: 235000.0


Question 16: Highest-Selling Store

Identify:

Index of the store with the highest total sales

Name of the store

Total sales generated by that store

Use np.argmax().

In [ ]:
total_sales= np.sum(sales_data, axis = 1)
highest_sales_store_index = np.argmax(total_sales)
print("Index of highest total sales store:",highest_sales_store_index)
print("Name of store:", stores[highest_sales_store_index])
print("Total sales:", total_sales[highest_sales_store_index])


Index of highest total sales store: 3
Name of store: Mumbai
Total sales: 2820000


Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales.

Use np.argmin().

In [ ]:
total_sales = np.sum(sales_data, axis = 1)
lowest_sales_store = np.argmin(total_sales)
print("Lowest sales store:", lowest_sales_store)

Lowest sales store: 4


Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

In [ ]:
total_sales = np.sum(sales_data, axis = 0)
highest_total_index = np.argmax(total_sales)
print("Highest selling category index: ", highest_total_index)
print("Highest selling category: ", categories[highest_total_index])
print("total sales:", total_sales[highest_total_index])

Highest selling category index:  0
Highest selling category:  Electronics
total sales: 4290000


Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

In [ ]:
total_sales = np.sum(sales_data, axis = 0)
lowest_category_index = np.argmin(total_sales)
print("Index of lowest category :",lowest_category_index)
print("Lowest selling store: ",categories[lowest_category_index])
print("Sales:", total_sales[lowest_category_index])


Index of lowest category : 4
Lowest selling store:  Beauty
Sales: 1010000


Part 5: Cost Analysis

Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

In [ ]:
total_cost = np.sum(cost_data)
print("Company cost:", total_cost)

Company cost: 8600000


Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.



In [ ]:
store_cost = np.sum(sales_data, axis = 1)
print("Bengaluru:", store_cost[0])
print("Hyderabad:", store_cost[1])
print("Chennai:", store_cost[2])
print("Mumbai:", store_cost[3])
print("Pune:", store_cost[4])

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

In [ ]:
category_cost = np.sum(cost_data, axis = 0)
print("Electronics:", category_cost[0])
print("Groceries:", category_cost[1])
print("Clothing:", category_cost[2])
print("Furniture:", category_cost[3])
print("Beauty:", category_cost[4])
print("Sports:", category_cost[5])

Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000


Question 23: Most Expensive Store

Identify the store with the highest total operating cost.

In [ ]:
expensive_store = np.sum(cost_data, axis = 1)
highest_operating_cost = np.argmax(expensive_store)
print("Index of expensive store is:", highest_operating_cost)
print("Store name:",stores[highest_operating_cost])
print("Operating cost: ", expensive_store[highest_operating_cost])

Index of expensive store is: 3
Store name: Mumbai
Operating cost:  2065000


Question 24: Lowest-Cost Store

Identify the store with the lowest total cost

In [ ]:
cost_store = np.sum(cost_data, axis = 1)
lowest_cost_store  = np.argmin(cost_store)
print("Index of lowest cost store is:", lowest_cost_store)
print("Store name:", stores[lowest_cost_store])
print("Lowest total cost:", cost_store[lowest_cost_store])

Index of lowest cost store is: 4
Store name: Pune
Lowest total cost: 1475000


Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

In [ ]:
product_category  = np.sum(cost_data, axis = 0)
expensive_product_category = np.argmax(product_category)
print("Product name:", categories[expensive_product_category])
print("Cost is:", product_category[expensive_product_category] )

Product name: Electronics
Cost is: 3250000


Part 6: Profit Analysis Using Two Arrays

Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

Use:

profit_data = sales_data - cost_data

Display the complete profit matrix.

In [ ]:
profit_data = sales_data - cost_data
print("Complete profit matrix:",profit_data)

Complete profit matrix: [[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

In [ ]:
profit_data = sales_data - cost_data
store_profit = np.sum(profit_data, axis = 1)
print("Bengaluru:", store_profit[0])
print("Hyderabad:", store_profit[1])
print("Chennai:", store_profit[2])
print("Mumbai:", store_profit[3])
print("Pune:", store_profit[4])

Bengaluru: 605000
Hyderabad: 610000
Chennai: 600000
Mumbai: 755000
Pune: 505000


Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.

In [ ]:
profit_data = sales_data - cost_data
category_profit = np.sum(profit_data, axis = 0)
print("Electronics:", category_profit[0])
print("Groceries:", category_profit[1])
print("Clothing:", category_profit[2])
print("Furniture:", category_profit[3])
print("Beauty:", category_profit[4])
print("Sports:", category_profit[5])

Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000


Question 29: Most Profitable Store

Identify the store that generated the highest total profit.

Display:

Store name

Total sales

Total cost

Total profit

In [ ]:
store_sales = np.sum(sales_data, axis = 1)
store_cost = np.sum(cost_data, axis = 1)
store_profit = store_sales - store_cost
highest_profit = np.argmax(store_profit)
print("Store name:", stores[highest_profit])
print("Total sales:", store_sales[highest_profit])
print("Total cost:", store_cost[highest_profit])
print("Total profit:", store_profit[highest_profit])

Store name: Mumbai
Total sales: 2820000
Total cost: 2065000
Total profit: 755000


Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

In [ ]:
store_sales = np.sum(sales_data, axis = 1)
store_cost = np.sum(cost_data, axis = 1)
store_profit = store_sales - store_cost
least_profit = np.argmin(store_profit)
print("Store name:", stores[least_profit])
print("Lowest profit store:", store_profit[least_profit])


Store name: Pune
Lowest profit store: 505000


Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

In [ ]:
category_sales = np.sum(sales_data, axis = 0)
category_cost = np.sum(cost_data, axis = 0)
category_profit = category_sales - category_cost
highest_category_profit = np.argmax(category_profit)
print("Category:", categories[highest_category_profit])
print("Highest total profit:", category_profit[highest_category_profit])

Category: Electronics
Highest total profit: 1040000


Question 32: Least Profitable Category

Find the category with the lowest total profit.

In [ ]:
category_sales = np.sum(sales_data, axis = 0)
category_cost = np.sum(cost_data, axis = 0)
category_profit = category_sales - category_cost
lowest_category_profit = np.argmin(category_profit)
print("Category:", categories[lowest_category_profit])
print("Lowest category profit:", category_profit[lowest_category_profit])


Category: Sports
Lowest category profit: 340000


Question 33: Maximum Individual Profit

Find the highest profit generated by any single store-category combination.

Display:

Profit amount

Store name

Product category

Use np.unravel_index().

In [ ]:
profit_data = sales_data - cost_data
maximum_index = np.unravel_index(np.argmax(profit_data), profit_data.shape)
store_index = maximum_index[0]
category_index = maximum_index[1]
print("Profit:", profit_data[store_index, category_index])
print("Store name:", stores[store_index])
print("Product category:", categories[category_index])


Profit: 260000
Store name: Mumbai
Product category: Electronics


Question 34: Minimum Individual Profit

Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [ ]:
profit_data = sales_data - cost_data
minimum_index = np.unravel_index(np.argmin(profit_data), profit_data.shape)
store_index = minimum_index[0]
category_index = minimum_index[1]
print("Store:", stores[store_index])
print("Category:", categories[category_index])
print("Profit:", profit_data[store_index, category_index])


Store: Pune
Category: Furniture
Profit: 55000


Part 7: Profit Margin Analysis

Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination.

Use:

profit_margin = (profit_data / sales_data) * 100

Round the result to two decimal places.

In [ ]:
profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100
print("Profit margin percentage:", np.round(profit_margin, 2))


Profit margin percentage: [[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using:

Store Profit Margin =

Total Store Profit / Total Store Sales × 100

In [ ]:
store_sales = np.sum(sales_data, axis = 1)
profit_data = sales_data - cost_data
store_profit = np.sum(profit_data, axis = 1)
store_profit_margin = (store_profit / store_sales) * 100
print("Overall profit percentage:", store_profit_margin)

Overall profit percentage: [26.65198238 26.5795207  25.97402597 26.77304965 25.50505051]


Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

In [ ]:
category_sales = np.sum(sales_data, axis = 0)
profit_data = sales_data - cost_data
category_profit = np.sum(profit_data, axis = 0)
category_profit_margin = (category_profit / category_sales) * 100
print("Category- wise profit percentage:", np.round(category_profit_margin, 2))


Category- wise profit percentage: [24.24 24.03 28.44 26.15 34.16 28.94]


Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

In [ ]:
store_sales = np.sum(sales_data, axis = 1)
profit_data = sales_data - cost_data
store_profit = np.sum(profit_data, axis = 1)
profit_margin = (store_profit / store_sales) * 100
highest_profit_margin = np.argmax(profit_margin)
print("Store:", stores[highest_profit_margin])
print("Highest overall profit margin:", np.round(profit_margin[highest_profit_margin], 2))



Store: Mumbai
Highest overall profit margin: 26.77


Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

In [ ]:
category_sales = np.sum(sales_data, axis = 0)
profit_data = sales_data - cost_data
category_profit = np.sum(profit_data, axis = 0)
profit_margin = (category_profit / category_sales) * 100
highest_category_margin = np. argmax(profit_margin)
print("Category:", categories[highest_profit_margin])
print("Highest profit margin:", np.round(profit_margin[highest_profit_margin], 2))

Category: Furniture
Highest profit margin: 26.15


Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store

Category

Sales

Cost

Profit

Profit margin

Use Boolean indexing.

In [ ]:
profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100
low_margin = profit_margin < 22
rows, columns = np.where(low_margin)
for i in range(len(rows)):
  row = rows[i]
  col = columns[i]
  print("Store:", stores[row])
  print("category:", categories[col])
  print("Sales:", sales_data[row, col])
  print("Cost:", cost_data[row, col])
  print("Profit margin:", round(profit_margin[row, col], 2))
  print()


Part 8: Boolean Filtering

Question 41: High Sales Values

Find all sales values greater than ₹5,00,000.

In [ ]:
high_sales = sales_data[sales_data > 500000]
print("Sales values:", high_sales)

Sales values: [ 850000  780000  920000 1050000  510000  690000]


Question 42: Low Sales Values

Find all sales values below ₹2,00,000.

In [ ]:
low_sales = sales_data[sales_data < 200000]
print("Low sales:", low_sales)

Low sales: [190000 185000 175000]


Question 43: High Profit Values

Find all store-category combinations where profit is greater than ₹1,50,000.

In [ ]:
profit_data = sales_data - cost_data
high_profit_values = profit_data > 150000
rows , columns = np.where(high_profit_values)
for i in range(len(rows)):
  row = rows[i]
  col = columns[i]
  print("Store:", stores[row])
  print("Category:", categories[col])
  print("profit:", profit_data[row, col])

Store: Bengaluru
Category: Electronics
profit: 210000
Store: Hyderabad
Category: Electronics
profit: 190000
Store: Chennai
Category: Electronics
profit: 220000
Store: Mumbai
Category: Electronics
profit: 260000
Store: Pune
Category: Electronics
profit: 160000


Question 44: Moderate Sales Range

Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

In [ ]:
moderate_sales = sales_data[np.logical_and(sales_data >= 250000, sales_data <= 500000)]
print("Sales between 250000 and 500000 are:", moderate_sales)

Sales between 250000 and 500000 are: [420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


Question 45: Premium Performance

A store-category combination is considered premium when:

Sales are greater than ₹5,00,000

Profit is greater than ₹1,50,000

Find all premium-performing combinations.

In [ ]:
profit_data = sales_data - cost_data
premium = np.logical_and(
    sales_data > 50000,
    profit_data > 150000
)
rows, columns = np.where(premium)
for i in range(len(rows)):
  row = rows[i]
  col = columns[i]
  print("Store: ", stores[row])
  print("Category: ", categories[col])
  print("Sales: ", sales_data[row, col])
  print("Profit: ", profit_data[row, col])


Store:  Bengaluru
Category:  Electronics
Sales:  850000
Profit:  210000
Store:  Hyderabad
Category:  Electronics
Sales:  780000
Profit:  190000
Store:  Chennai
Category:  Electronics
Sales:  920000
Profit:  220000
Store:  Mumbai
Category:  Electronics
Sales:  1050000
Profit:  260000
Store:  Pune
Category:  Electronics
Sales:  690000
Profit:  160000


Question 46: Underperforming Combinations

A store-category combination is considered underperforming when:

Sales are below ₹2,50,000

Profit margin is below 25%

Find all such combinations.

In [ ]:
profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100
underperforming = np.logical_and(
    sales_data < 250000,
    profit_margin < 25
)
rows, columns = np.where(underperforming)
for i in range(len(rows)):
  row = rows[i]
  col = columns[i]
  print("Store:", stores[row])
  print("Category:", categories[col])
  print("Sales:", sales_data[row,col])
  print("Profit:", profit_data[row, col])
  print("Profit margin:", profit_margin[row, col])


Store: Pune
Category: Furniture
Sales: 225000
Profit: 55000
Profit margin: 24.444444444444443


Question 47: Category Performance Classification

Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000

"Medium" when sales are between ₹2,50,000 and ₹4,99,999

"Low" when sales are below ₹2,50,000

Use np.where() or np.select().

In [ ]:
performance = [
    sales_data >= 500000,
    np.logical_and(sales_data >= 250000, sales_data < 500000),
    sales_data < 250000
]
options = ["High", "Medium", "Low"]
classification = np.select(performance, options, default = "unknown")
classification

array([['High', 'Medium', 'Medium', 'Medium', 'Low', 'Low'],
       ['High', 'Medium', 'Medium', 'Medium', 'Low', 'Low'],
       ['High', 'Medium', 'Medium', 'Medium', 'Low', 'Low'],
       ['High', 'High', 'Medium', 'Medium', 'Medium', 'Medium'],
       ['High', 'Medium', 'Medium', 'Low', 'Low', 'Low']], dtype='<U7')

Part 9: Target-Based Analysis

Use the following category-wise monthly sales targets:

sales_targets = np.array([
    
    800000,  # Electronics
    
    450000,  # Groceries
    
    320000,  # Clothing
    
    300000,  # Furniture
    
    200000,  # Beauty
    
    230000   # Sports
])

Question 48: Target Comparison

Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [ ]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
comparison = sales_data >= sales_targets
comparison

array([[ True, False, False, False, False, False],
       [False,  True, False,  True,  True,  True],
       [ True, False,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False]])

Question 49: Target Achievement Matrix

Create a Boolean array where:

True means the store achieved the category target

False means the store failed to achieve the target

In [ ]:
target = sales_data >= sales_targets
target

array([[ True, False, False, False, False, False],
       [False,  True, False,  True,  True,  True],
       [ True, False,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False]])

Question 50: Target Achievement Count

Calculate the number of categories in which each store achieved its target.

In [ ]:
target = sales_data >= sales_targets
count = np.sum(target, axis = 1)
print("Count:",count)

Count: [1 4 2 6 0]


Question 51: Best Target-Performing Store

Find the store that achieved the highest number of category targets.

In [ ]:
store = np.argmax(count)
print("Store count:", store)
print("Store name:", stores[store])

Store count: 3
Store name: Mumbai


Question 52: Target Achievement by Category

Calculate how many stores achieved the target for each product category.

In [ ]:
target = sales_data >= sales_targets
stores_acheived = np.sum(target, axis = 0)
print("Stores:", stores_acheived)

Stores: [3 2 2 2 2 2]


Question 53: Sales Target Variance

Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales

In [ ]:
var = sales_data - sales_targets
print(var)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


Question 54: Percentage Above or Below Target

Calculate the percentage variance from the target using:

Percentage Variance =

(Actual Sales - Target Sales) / Target Sales × 100

In [ ]:
var_percentage = (sales_data - sales_targets) / sales_targets * 100
print(var_percentage)

[[  6.25        -6.66666667  -3.125       -8.33333333  -5.
   -2.17391304]
 [ -2.5          2.22222222  -7.8125       3.33333333   5.
    4.34782609]
 [ 15.         -13.33333333   6.25       -13.33333333  -7.5
   -6.52173913]
 [ 31.25        13.33333333  17.1875      15.          25.
   26.08695652]
 [-13.75       -10.         -12.5        -25.         -12.5
  -10.86956522]]


Question 55: Stores Missing Electronics Target

Identify stores that failed to achieve the Electronics sales target.

In [ ]:
target = sales_targets[0]
failed_stores = stores[sales_data[:, 0] < target]
print(failed_stores)

['Hyderabad' 'Pune']


Question 56: Stores Achieving All Targets

Check whether any store achieved its target in all six product categories.

Use np.all().

In [ ]:
target = sales_data >= sales_targets
all_targets = np.all(target, axis = 1)
print(all_targets)

[False False False  True False]


Question 57: Stores Achieving At Least One Target

Identify stores that achieved at least one category target.

Use np.any().

In [ ]:
target = sales_data >= sales_targets
stores_achieved = np.any(target, axis = 1)
print(stores_achieved)

[ True  True  True  True False]


Part 10: Discount Scenario

SmartMart plans to offer category-wise discounts:

discount_rates = np.array([

    0.10,  # Electronics: 10%

    0.05,  # Groceries: 5%

    0.15,  # Clothing: 15%

    0.12,  # Furniture: 12%


    0.08,  # Beauty: 8%

    0.10   # Sports: 10%

])

Question 58: Discount Amount Matrix

Calculate the discount amount for each store-category combination.

Use broadcasting.

In [ ]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])
discount_amount = sales_data * discount_rates
print(discount_amount)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


Question 59: Sales After Discount

Calculate the net sales value after applying the category-wise discounts.

In [ ]:
sales_after_discount = sales_data - discount_amount
print(sales_after_discount)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


Question 60: Profit After Discount

Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [ ]:
new_profit = sales_after_discount - cost_data
print(new_profit)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


Question 61: Profit Margin After Discount

Calculate the new profit margin after applying discounts.

In [ ]:
profit_margin = (new_profit / sales_after_discount) * 100
print(np.round(profit_margin, 2))

[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


Question 62: Loss-Making Transactions

Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [ ]:
affected_store =  sales_data - sales_after_discount
print(affected_store)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


Question 63: Discount Impact

Calculate how much total revenue the company loses because of the proposed discounts.

In [ ]:
revenue_loss = np.sum(affected_store)
print(revenue_loss)

1146350.0


Question 64: Store Most Affected by Discounts

Identify the store that loses the highest amount of revenue due to discounts.

In [ ]:
total_discount = np.sum(affected_store, axis = 1)
highest_affected_store = stores[np.argmax(total_discount)]
print(highest_affected_store)

Mumbai


Part 11: Tax and Price Adjustment

The government introduces category-wise tax rates:

tax_rates = np.array([

    0.18,

    0.05,

    0.12,

    0.18,

    0.18,


    0.12
])

Question 65: Tax Collection Matrix

Calculate the tax collected on sales for each store and category.

In [ ]:
tax_rates = np.array([

0.18,

0.05,

0.12,

0.18,

0.18,


0.12
])
tax_collected = sales_data * tax_rates
print(tax_collected)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


Question 66: Sales Including Tax

Calculate the final customer billing value after adding tax.

In [ ]:
sales_including_tax = sales_data + tax_collected
print(sales_including_tax)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


Question 67: Store-Wise Tax Collection

Calculate the total tax collected by each store.

In [ ]:
store_wise_tax = np.sum(tax_collected, axis = 1)
print(store_wise_tax)

[321900. 321200. 331800. 401400. 274650.]


Question 68: Category-Wise Tax Collection

Calculate total tax collected for each category.

In [ ]:
category_wise_tax = np.sum(tax_collected, axis = 0)
print(category_wise_tax)

[772200. 109250. 192000. 254700. 181800. 141000.]


Question 69: Highest Tax-Contributing Store

Identify the store that contributes the highest tax amount.

In [ ]:
highest_tax_store = stores[np.argmax(store_wise_tax)]
print(highest_tax_store)

Mumbai


Part 12: Array Modification

Question 70: Updated Pune Electronics Sales

The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [ ]:
updated_pune_sales = sales_data.copy()
updated_pune_sales[4, 0] = 740000
print(updated_pune_sales)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


Question 71: Revised Beauty Cost

Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [ ]:
updated_cost = cost_data.copy()
updated_cost[:, 4] = updated_cost[:, 4] * 0.92
print(updated_cost)

[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


Question 72: Furniture Cost Increase

Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [ ]:
update_furniture_cost = cost_data.copy()
update_furniture_cost[:, 3] = update_furniture_cost[:, 3] * 1.12
print(update_furniture_cost)


[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


Question 73: Store Closure Simulation

Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

In [ ]:
remove_sales_pune = np.delete(sales_data, 4, axis = 0)
remove_cost_pune = np.delete(cost_data, 4, axis = 0)
print("After removing pune sales:", remove_sales_pune)
print("After removing pune cost data:", remove_cost_pune)

After removing pune sales: [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
After removing pune cost data: [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


Question 74: Adding a New Store

A new Delhi store is opened with the following data:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

In [ ]:
sales_with_delhi = np.vstack((sales_data, delhi_sales))
cost_with_delhi = np.vstack((cost_data, delhi_cost))
stores_with_delhi = np.append(stores, "Delhi")
print("Sales data:",sales_with_delhi)
print("Cost data:", cost_with_delhi)
print("\nStores:",stores_with_delhi)

Sales data: [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
Cost data: [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]

Stores: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']


Question 75: Adding a New Product Category

SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([
   
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
   
    265000,
    240000,
    285000,
    305000,
    225000
])

Add the new category as a column using np.column_stack() or np.hstack().

In [ ]:
sales_with_home_appliances = np.column_stack((sales_data, home_appliance_sales))
cost_with_home_appliances = np.column_stack((cost_data, home_appliance_cost))
print("Sales data:", sales_with_home_appliances)
print("Cost data:", cost_with_home_appliances)

Sales data: [[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
Cost data: [[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


Part 13: Sorting and Ranking

Question 76: Sort Stores by Sales

Sort stores in ascending order based on total sales.

Display store names and sales totals.


In [ ]:
total_sales = np.sum(sales_data, axis = 1)
sorted_index = np.argsort(total_sales)
sorted_stores = stores[sorted_index]
sorted_sales =  total_sales[sorted_index]
print("Stores:", sorted_stores)
print("Sales:", sorted_sales)


Stores: ['Pune' 'Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']
Sales: [1980000 2270000 2295000 2310000 2820000]


Question 77: Rank Stores by Profit

Rank stores from highest to lowest total profit.

Use np.argsort().

In [ ]:
profit_data = sales_data - cost_data
profit = np.sum(profit_data, axis = 1)
sort_stores = np.argsort(profit)[::-1]
print("Stores ranked from highest:", stores[sort_stores])
print(profit[sort_stores])


Stores ranked from highest: ['Mumbai' 'Hyderabad' 'Bengaluru' 'Chennai' 'Pune']
[755000 610000 605000 600000 505000]


Question 78: Sort Categories by Revenue

Sort product categories from highest to lowest total revenue.

In [ ]:
revenue = np.sum(sales_data, axis = 0)
sort_category = np.argsort(revenue)[::-1]
print("Categories:", categories[sort_category])

Categories: [3250000 1660000 1145000 1045000  835000  665000]


Question 79: Top Three Store-Category Sales

Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value

Store name

Category name

In [ ]:
index = np.argsort(sales_data.flatten())[-3:][::-1]
rows, columns = np.unravel_index(index, sales_data.shape)
for i in range(3):
  print("Sales value:", sales_data[rows[i], columns[i]],
        "Store name:", stores[rows[i]],
       "Category name:", categories[columns[i]])

Sales value: 1050000 Store name: Mumbai Category name: 3250000
Sales value: 920000 Store name: Chennai Category name: 3250000
Sales value: 850000 Store name: Bengaluru Category name: 3250000


Question 80: Bottom Three Profits

Find the three lowest profit values in the profit matrix.

In [ ]:
profit_data = sales_data - cost_data
index = np.argsort(profit_data.flatten())[:3]
for i in index:
  print(profit_data.flatten()[i])

55000
60000
60000


Part 14: Statistical Analysis

Question 81: Sales Statistics

Calculate the following for the complete sales array:

Minimum

Maximum

Mean

Median

Standard deviation

Variance

25th percentile

50th percentile

75th percentile

In [ ]:
sales = sales_data.flatten()
print("Minimum:", np.min(sales))
print("Maximum:", np.max(sales))
print("Mean:", np.mean(sales))
print("Median:", np.median(sales))
print("Standard deviation: ", np.std(sales))
print("Variance:", np.var(sales))
print("25th percentile:", np.percentile(sales, 25))
print("50th percentile:", np.percentile(sales, 50))
print("75th percentile:", np.percentile(sales, 75))

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard deviation:  230322.53954448793
Variance: 53048472222.222206
25th percentile: 228750.0
50th percentile: 302500.0
75th percentile: 416250.0


Question 82: Store-Wise Standard Deviation

Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [ ]:
std_deviation = np.std(sales_data, axis = 1)
high_variation = np.argmax(std_deviation)
print("Store wise standard deviation:", std_deviation)
print("Store with highest variation:",stores[high_variation])
print("Highest standard deviation:", std_deviation[high_variation])

Store wise standard deviation: [223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]
Store with highest variation: Mumbai
Highest standard deviation: 271860.871280391


Question 83: Category-Wise Standard Deviation

Determine which product category has the highest variation in sales across stores.

In [ ]:
std_deviation = np.std(sales_data, axis = 0)
high_variation = np.argmax(std_deviation)
print("category wise standard deviation:", std_deviation)
print("Category with highest standard deviation:", categories[high_variation])
print("Highest standard deviation:", std_deviation[high_variation])

category wise standard deviation: [122539.78945632  43312.81565542  33911.64991563  41303.75285613
  26570.66051117  29832.86778035]
Category with highest standard deviation: 3250000
Highest standard deviation: 122539.78945632312


Question 84: Sales Above Company Average

Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

In [ ]:
sales_avg = np.average(sales_data )
above_avg = np.sum(sales_data > sales_avg)
print("Company wide avg sales:", sales_avg)
print("Number of sales above avg: ",)

Company wide avg sales: 389166.6666666667
Number of sales above avg:  10


Question 85: Outlier Detection

Treat any sales value greater than:

Mean + 1.5 × Standard Deviation

as a high-value outlier.

Identify all such sales values.

In [ ]:
mean = np.mean(sales_data)
std = np.std(sales_data)
threshold = mean + 1.5 * std
outlier = sales_data[sales_data > threshold]
print("Mean:", mean)
print("Standard deviation:", std)
print("Threshold:", threshold)
print("Highest outliers:", outlier)

Mean: 389166.6666666667
Standard deviation: 230322.53954448793
Threshold: 734650.4759833985
Highest outliers: [ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation

Question 86: Flatten Sales Data

Convert the two-dimensional sales array into a one-dimensional array using:

flatten()

ravel()

Explain the difference between the two methods.

In [ ]:
sales_flatten = sales_data.flatten()
sales_ravel = sales_data.ravel()
print(sales_flatten)
print(sales_ravel)

[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


Question 87: Reshape Sales Data

Reshape the 5 × 6 sales array into:

3 × 10

10 × 3

2 × 15

15 × 2

Verify that no data is lost.

In [ ]:
sales_3x10 = sales_data.reshape(3, 10)
sales_10x3 = sales_data.reshape(10, 3)
sales_2x15 = sales_data.reshape(2, 15)
sales_15x2 = sales_data.reshape(15, 2)
print(sales_3x10)
print(sales_10x3)
print(sales_2x15)
print(sales_15x2)
print("Original array:", sales.size)
print("3x10:", sales_3x10.size)
print("10x3:", sales_10x3.size)
print("2x15:", sales_2x15.size)
print("15x2:", sales_15x2.size)


[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  510000]
 [ 375000  345000]
 [ 250000  29

Question 88: Transpose Sales Data

Transpose the sales array so that:

Rows represent product categories

Columns represent stores

Display the new shape.

In [ ]:
transpose = sales_data.T
print(transpose)
print("New shape:", transpose.shape)

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
New shape: (6, 5)


Question 89: Combined Sales and Cost Array

Stack sales_data and cost_data vertically.

Display the resulting shape.

In [ ]:
combined = np.vstack((sales_data, cost_data))
print(combined)
print("Shape:", combined.shape)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
Shape: (10, 6)


Question 90: Store-Level Combined Data

Create a three-dimensional array where:

First layer contains sales data

Second layer contains cost data

Use np.stack().

Display the shape of the new array.

In [ ]:
combined = np.stack((sales_data, cost_data))
print(combined)
print(combined.shape)

[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
(2, 5, 6)


Part 16: Missing Data Scenario

The company discovers that some sales values were not recorded.

sales_with_missing = np.array([

    [850000, 420000, np.nan, 275000, 190000, 225000],

    [780000, 460000, 295000, np.nan, 210000, 240000],

    [920000, 390000, 340000, 260000, 185000, 215000],

    [1050000, np.nan, 375000, 345000, 250000, 290000],

    [690000, 405000, 280000, 225000, np.nan, 205000]

])

Question 91: Missing Value Detection

Find:

Total number of missing values

Location of missing values

Stores and categories containing missing values

In [ ]:
sales_with_missing = np.array([

[850000, 420000, np.nan, 275000, 190000, 225000],

[780000, 460000, 295000, np.nan, 210000, 240000],

[920000, 390000, 340000, 260000, 185000, 215000],

[1050000, np.nan, 375000, 345000, 250000, 290000],

[690000, 405000, 280000, 225000, np.nan, 205000]
])
missing_values = np.isnan(sales_with_missing)
total_missing_val = np.sum(missing_values)
rows, columns = np.where(missing_values)
for i in range(len(rows)):
  print("Rows: ", rows[i],
        "Columns: ", columns[i],
        " Stores: ", stores[rows[i]],
        "  Categories: ", categories[columns[i]])


Rows:  0 Columns:  2  Stores:  Bengaluru   Categories:  1145000
Rows:  1 Columns:  3  Stores:  Hyderabad   Categories:  1045000
Rows:  3 Columns:  1  Stores:  Mumbai   Categories:  1660000
Rows:  4 Columns:  4  Stores:  Pune   Categories:  665000


Question 92: Replace Missing Values with Zero

Replace all missing sales values with zero.

In [ ]:
missing_val = np.isnan(sales_with_missing)
sales_with_missing[missing_val] = 0
print("After replacing values: ", sales_with_missing)

After replacing values:  [[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 93: Replace with Company Average

Replace missing values with the overall average of available sales values.

Use np.nanmean().

In [ ]:
sales_with_missing = np.array([

[850000, 420000, np.nan, 275000, 190000, 225000],

[780000, 460000, 295000, np.nan, 210000, 240000],

[920000, 390000, 340000, 260000, 185000, 215000],

[1050000, np.nan, 375000, 345000, 250000, 290000],

[690000, 405000, 280000, 225000, np.nan, 205000]
])
sales_avg= np.nanmean(sales_with_missing)
sales_with_missing[np.isnan(sales_with_missing)] = sales_avg
print("Average:", sales_avg)
print(sales_with_missing)

Average: 398846.1538461539
[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


Question 94: Replace with Category Average

Replace each missing value with the average sales value of its respective product category.

In [ ]:
category_avg = np.nanmean(sales_with_missing, axis = 0)
for i in range(sales_with_missing.shape[0]):
  for j in range(sales_with_missing.shape[1]):
    if np.isnan(sales_with_missing[i, j]):
      sales_with_missing[i, j]= category_avg[j]
print("Category average:", category_avg)
print("After replacing values:", sales_with_missing)


Category average: [858000.         414769.23076923 337769.23076923 300769.23076923
 246769.23076923 235000.        ]
After replacing values: [[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


Question 95: Missing Value Impact

Compare total sales before and after replacing missing values with zero.

In [ ]:
total_before = np.nansum(sales_with_missing)
sales_zero = np.nan_to_num(sales_with_missing, nan =0 )
total_after = np.sum(sales_zero)
print("Total before:", total_before)
print("Total after:", total_after)
print("Difference:", total_before - total_after)

Total before: 11965384.615384616
Total after: 11965384.615384616
Difference: 0.0


Part 17: Conditional Business Decisions

Question 96: Store Performance Labels

Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000

"Good": Total sales between ₹24,00,000 and ₹28,00,000

"Needs Improvement": Total sales below ₹24,00,000

Use np.select().



In [ ]:
store_sales = np.sum(sales_data, axis = 1)
conditions = [
    store_sales > 2800000,
    (store_sales >= 2400000) & (store_sales <= 2800000),
    store_sales < 2400000
]
labels = ["Exccellent", "Good", "Needs Improvement"]
performance = np.select(conditions, labels, default = "unknown")
print("Store total sales:", store_sales)
print("Store performance:", performance)

Store total sales: [2270000 2295000 2310000 2820000 1980000]
Store performance: ['Needs Improvement' 'Needs Improvement' 'Needs Improvement' 'Exccellent'
 'Needs Improvement']


Question 97: Profitability Classification

Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000

"Profitable": Profit between ₹1,00,000 and ₹2,00,000

"Low Profit": Profit below ₹1,00,000

"Loss": Profit below zero

In [ ]:
profit_data = sales_data - cost_data
conditions = [
    profit_data < 0,
    profit_data < 100000,
    profit_data <= 200000,
    profit_data > 200000
]
labels = ["Loss", "Low Profit", "Profitable", "Highly Profitable"]
profit_class = np.select(conditions, labels, default = "unknown")
print(profit_data)
print(profit_class)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]
[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


Question 98: Expansion Recommendation

A store is eligible for expansion when:

Total sales are above ₹25,00,000

Total profit is above ₹7,00,000

Overall profit margin is above 25%

Identify eligible stores.

In [ ]:
total_sales = np.sum(sales_data, axis = 1)
profit_data = sales_data - cost_data
total_profit = np.sum(profit_data, axis =1)
profit_margin = (total_profit / total_sales) * 100
eligible = (
    (total_sales> 2500000)  &
    (total_profit > 700000) &
    (profit_margin > 25)
    )
eligible_stores = stores[eligible]
print("total sales:", total_sales)
print("total profit:", total_profit)
print("profit margin:", profit_margin)
print("eligible stores:", eligible_stores)


total sales: [2270000 2295000 2310000 2820000 1980000]
total profit: [605000 610000 600000 755000 505000]
profit margin: [26.65198238 26.5795207  25.97402597 26.77304965 25.50505051]
eligible stores: ['Mumbai']


Question 99: Category Promotion Recommendation

A product category should receive additional promotion when:

Average sales are below ₹3,00,000

Profit margin is above 25%

Identify the categories that satisfy these conditions.

In [ ]:
avg_sales = np.average(sales_data, axis = 0)
profit_data = sales_data - cost_data
total_profit = np.sum(profit_data, axis =0)
total_sales = np.sum(sales_data, axis = 0)
profit_margin = (total_profit / total_sales) * 100
promotion = (
    (avg_sales < 300000) &
    (profit_margin > 25)
)
promotion_categories = categories[promotion]
print("Average sales:", avg_sales)
print("Profit margin:", profit_margin)
print("promotion for categories:", promotion_categories)

Average sales: [858000. 437000. 320000. 283000. 202000. 235000.]
Profit margin: [24.24242424 24.02745995 28.4375     26.14840989 34.15841584 28.93617021]
promotion for categories: ['Furniture' 'Beauty' 'Sports']


Question 100: Cost Optimization Recommendation

Find store-category combinations where:

Cost is greater than ₹2,50,000

Profit margin is below 25%

These combinations should be reviewed for cost optimization.

In [ ]:
profit_data = sales_data - cost_data
total_profit = np.sum(profit_data, axis = 0)
profit_margin = (profit_data / sales_data) * 100
conditions = (cost_data > 250000) & ( profit_margin < 25)
rows, columns = np.where(conditions)
for i in range(len(rows)):
  print("Store:", stores[rows[i]])
  print("categories:", categories[columns[i]])
  print("cost:", cost_data[rows[i], columns[i]])
  print("profit margin:", profit_margin[rows[i], columns[i]])


Store: Bengaluru
categories: Electronics
cost: 640000
profit margin: 24.705882352941178
Store: Hyderabad
categories: Electronics
cost: 590000
profit margin: 24.358974358974358
Store: Hyderabad
categories: Groceries
cost: 350000
profit margin: 23.91304347826087
Store: Chennai
categories: Electronics
cost: 700000
profit margin: 23.91304347826087
Store: Chennai
categories: Groceries
cost: 295000
profit margin: 24.358974358974358
Store: Mumbai
categories: Electronics
cost: 790000
profit margin: 24.761904761904763
Store: Mumbai
categories: Groceries
cost: 390000
profit margin: 23.52941176470588
Store: Pune
categories: Electronics
cost: 530000
profit margin: 23.18840579710145
Store: Pune
categories: Groceries
cost: 310000
profit margin: 23.456790123456788


Part 18: Inventory Scenario

Use the following inventory arrays:

opening_stock = np.array([

    [120, 450, 300, 90, 250, 180],

    [110, 500, 280, 100, 270, 200],

    [130, 420, 320, 85, 240, 170],

    [150, 550, 350, 120, 300, 220],

    [100, 400, 260, 75, 220, 160]

])

units_sold = np.array([

    [95, 380, 240, 65, 190, 140],

    [85, 420, 230, 75, 210, 155],

    [105, 350, 270, 60, 180, 130],


    [125, 470, 295, 90, 235, 175],

    [75, 330, 205, 55, 165, 120]
])

Question 101: Closing Stock

Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [4]:
opening_stock = np.array([

[120, 450, 300, 90, 250, 180],

[110, 500, 280, 100, 270, 200],

[130, 420, 320, 85, 240, 170],

[150, 550, 350, 120, 300, 220],

[100, 400, 260, 75, 220, 160]
])

units_sold = np.array([

[95, 380, 240, 65, 190, 140],

[85, 420, 230, 75, 210, 155],

[105, 350, 270, 60, 180, 130],


[125, 470, 295, 90, 235, 175],

[75, 330, 205, 55, 165, 120]
])
closing_stock = opening_stock - units_sold
print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 102: Low-Stock Identification

Identify store-category combinations where closing stock is below 30 units.



In [ ]:
closing_stock = opening_stock - units_sold
rows, columns = np.where(closing_stock < 30 )
for i in range(len(rows)):
  print("Stores:", stores[rows[i]])
  print("category:", categories[columns[i]])
  print("closing stock:", closing_stock[rows[i], columns[i]])


Stores: Bengaluru
category: Electronics
closing stock: 25
Stores: Bengaluru
category: Furniture
closing stock: 25
Stores: Hyderabad
category: Electronics
closing stock: 25
Stores: Hyderabad
category: Furniture
closing stock: 25
Stores: Chennai
category: Electronics
closing stock: 25
Stores: Chennai
category: Furniture
closing stock: 25
Stores: Mumbai
category: Electronics
closing stock: 25
Stores: Pune
category: Electronics
closing stock: 25
Stores: Pune
category: Furniture
closing stock: 20


Question 103: Stock Availability Percentage

Calculate the percentage of opening stock that remains unsold.

In [ ]:
stock_percentage = (closing_stock / opening_stock) * 100
print(stock_percentage)

[[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]


Question 104: Fast-Moving Products

A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [ ]:
sold_percentage = (units_sold / opening_stock) * 100
fast_moving = sold_percentage > 80
rows, columns = np.where(fast_moving)
for i in range(len(rows)):
  print("store:", stores[rows[i]])
  print("category:", categories[columns[i]])
  print("sold percentage:", sold_percentage[rows[i], columns[i]])

store: Bengaluru
category: Groceries
sold percentage: 84.44444444444444
store: Hyderabad
category: Groceries
sold percentage: 84.0
store: Hyderabad
category: Clothing
sold percentage: 82.14285714285714
store: Chennai
category: Electronics
sold percentage: 80.76923076923077
store: Chennai
category: Groceries
sold percentage: 83.33333333333334
store: Chennai
category: Clothing
sold percentage: 84.375
store: Mumbai
category: Electronics
sold percentage: 83.33333333333334
store: Mumbai
category: Groceries
sold percentage: 85.45454545454545
store: Mumbai
category: Clothing
sold percentage: 84.28571428571429
store: Pune
category: Groceries
sold percentage: 82.5


Question 105: Category-Wise Units Sold

Calculate the total units sold for each product category.

In [ ]:
total_units = np.sum(units_sold, axis = 0)
print(units_sold)

[[ 95 380 240  65 190 140]
 [ 85 420 230  75 210 155]
 [105 350 270  60 180 130]
 [125 470 295  90 235 175]
 [ 75 330 205  55 165 120]]


Question 106: Store-Wise Units Sold

Calculate total units sold by each store.

In [ ]:
store_units_sold = np.sum(units_sold, axis = 1)
print(store_units_sold)

[1110 1175 1095 1390  950]


Question 107: Best Store by Unit Sales

Identify the store that sold the highest total number of units.

In [ ]:
store_units_sold = np.sum(units_sold, axis =1)
best_store = np.argmax(store_units_sold)
print("total units sold:", store_units_sold)
print("best store:", best_store)
print("highest number of units sold:", store_units_sold[best_store])

total units sold: [1110 1175 1095 1390  950]
best store: 3
highest number of units sold: 1390


Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.



In [ ]:
closing_stock = opening_stock - units_sold
reorder = closing_stock < 25
print(closing_stock)
print("Matrix:",reorder)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]
Matrix: [[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity

Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [ ]:
closing_stock = opening_stock - units_sold
reorder_quantity = np.where(
    closing_stock < 25,
    100 - closing_stock,
    0
)
print(closing_stock)
print(reorder_quantity)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions

Question 110: Cumulative Store Sales

Calculate cumulative category sales for each store using np.cumsum().

In [ ]:
cumulative_store_sales = np.cumsum(sales_data, axis = 1)
print(cumulative_store_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


Question 111: Cumulative Company Sales

Flatten the sales array and calculate cumulative company sales.

In [ ]:
cumulative_flatten_sales = np.cumsum(sales_data.flatten())
print(cumulative_flatten_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


Question 112: Sales Difference Between Categories

Calculate the difference between consecutive category sales for each store using np.diff().

In [ ]:
difference = np.diff(sales_data, axis = 1)
difference

array([[-430000, -110000,  -35000,  -85000,   35000],
       [-320000, -165000,   15000, -100000,   30000],
       [-530000,  -50000,  -80000,  -75000,   30000],
       [-540000, -135000,  -30000,  -95000,   40000],
       [-285000, -125000,  -55000,  -50000,   30000]])

Question 113: Unique Sales Values

Find all unique sales values in sales_data.

Also count the frequency of each value.

In [ ]:
unique_values, frequency = np.unique(sales_data, return_counts = True)
print(unique_values)
print(frequency)

[ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
[1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]


Question 114: Search for Specific Sales

Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [ ]:
value = 420000
rows, columns = np.where(sales_data == value)
print("value_exists:", np.any(sales_data == value))
for i in range(len(rows)):
  print("stores:", stores[rows[i]])
  print("category:", categories[columns[i]])
  print("location:", (rows[i], columns[i]))

value_exists: True
stores: Bengaluru
category: Groceries
location: (np.int64(0), np.int64(1))


Question 115: Compare Sales and Cost

Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [ ]:
profitable = sales_data > cost_data
all_profitable = np.all(profitable)
print("sales greater than cost:",profitable)
print("all combinations profitable:", all_profitable)


sales greater than cost: [[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
all combinations profitable: True


Question 116: Clip Profit Values

For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000

Maximum: ₹2,50,000

Use np.clip() to create a reporting profit array.

In [ ]:
profit_data = sales_data - cost_data
reporting = np.clip(profit_data, 75000, 250000)
print("Profit data:",profit_data)
print("Reporting:",reporting)

Profit data: [[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]
Reporting: [[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


Question 117: Normalize Sales Data

Normalize all sales values using min-max normalization:

Normalized Sales =

(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

In [ ]:
max_sales = np.max(sales_data)
min_sales = np.min(sales_data)
normalized_sales = (sales_data - min_sales) / (max_sales - min_sales)
print("minimum sales:",min_sales)
print("maximum sales:",max_sales)
print("normalized sales:",normalized_sales)

minimum sales: 175000
maximum sales: 1050000
normalized sales: [[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


Question 118: Standardize Sales Data

Standardize sales using:

Standardized Sales =
(Sales - Mean Sales) / Standard Deviation

In [ ]:
mean_sales = np.mean(sales_data)
standard_deviation = np.std(sales_data)
standardized_sales = (sales_data - mean_sales) / standard_deviation
print("mean sales:", mean_sales)
print("standard deviation:", standard_deviation)
print("standardized sales:", standardized_sales)

mean sales: 389166.6666666667
standard deviation: 230322.53954448793
standardized sales: [[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


Question 119: Round Values

Convert profit margin values into:

Two decimal places

Nearest whole number

Floor values

Ceiling values

In [ ]:
total_sales = np.sum(sales_data, axis = 1)
profit_data = sales_data - cost_data
total_profit = np.sum(profit_data, axis=1)
profit_margin = (total_sales / total_profit) * 100
two_decimal = np.round(profit_margin, 2)
nearest_whole_num = np.round(profit_margin)
floor_val = np.floor(profit_margin)
ceil_val = np.ceil(profit_margin)
print(two_decimal)
print(nearest_whole_num)
print(floor_val)
print(ceil_val)

[375.21 376.23 385.   373.51 392.08]
[375. 376. 385. 374. 392.]
[375. 376. 385. 373. 392.]
[376. 377. 385. 374. 393.]


Question 120: Save and Load Data

Save the following arrays as NumPy binary files:

sales_data.npy

cost_data.npy

profit_data.npy

Load them back and verify that the loaded arrays are equal to the original arrays.

In [ ]:
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)
loaded_sales = np.load("sales_data.npy")
loaded_cost = np.load("cost_data.npy")
loaded_profit = np.load("profit_data.npy")
print("Sales data equal:", np.array_equal(sales_data, loaded_sales))
print("Cost data equal:", np.array_equal(cost_data, loaded_cost))
print("Profit data equal:", np.array_equal(profit_data, loaded_profit))

Sales data equal: True
Cost data equal: True
Profit data equal: True


Part 20: Final Retail Analytics Project

Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

Company Summary

Total company sales

Total company cost

Total company profit

Overall company profit margin

Average transaction value

Highest individual sales value

Lowest individual sales value


Store Summary

For every store, display:

Total sales

Total cost


Total profit
Profit margin

Number of category targets achieved

Total units sold

Expansion eligibility

Category Summary

For every category, display:


Total sales

Total cost

Total profit

Profit margin


Average sales

Number of stores achieving the target

Total units sold

Management Recommendations

Based on the analysis, identify:

Best-performing store

Lowest-performing store

Most profitable category

Lowest-profit category

Store recommended for expansion

Category requiring additional marketing

Store-category combinations needing cost optimization

Store-category combinations requiring inventory reorder

Expected Final Output Format

SMARTMART RETAIL PERFORMANCE REPORT
===================================

COMPANY SUMMARY
---------------
Total Sales:

Total Cost:

Total Profit:

Overall Profit Margin:

BEST-PERFORMING STORE
---------------------
Store:

Sales:

Cost:

Profit:

Profit Margin:

MOST PROFITABLE CATEGORY
------------------------
Category:

Sales:

Cost:

Profit:

Profit Margin:

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores:

COST OPTIMIZATION
-----------------
Store:

Category:

Cost:

Profit Margin:

INVENTORY REORDER
-----------------
Store:

Category:

Closing Stock:

Reorder Quantity:

In [8]:
import numpy as np
profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100
# COMPANY SUMMARY
total_sales = np.sum(sales_data)
total_cost = np.sum(cost_data)
total_profit = np.sum(profit_data)
overall_profit_margin = (total_profit / total_sales) * 100
average_transaction = np.mean(sales_data)
highest_sales = np.max(sales_data)
lowest_sales = np.min(sales_data)
# STORE SUMMARY CALCULATIONS
store_sales = np.sum(sales_data, axis=1)
store_cost = np.sum(cost_data, axis=1)
store_profit = np.sum(profit_data, axis=1)
store_profit_margin = (store_profit / store_sales) * 100
store_units_sold = np.sum(units_sold, axis=1)
# TARGET ACHIEVEMENT
target = np.array([
    800000,
    400000,
    300000,
    300000,
    200000,
    220000
])
target_achievement = sales_data >= target
store_target_count = np.sum(
    target_achievement,
    axis=1
)
category_target_count = np.sum(
    target_achievement,
    axis=0
)
# CATEGORY SUMMARY CALCULATIONS
category_sales = np.sum(
    sales_data,
    axis=0
)
category_cost = np.sum(
    cost_data,
    axis=0
)
category_profit = np.sum(
    profit_data,
    axis=0
)
category_profit_margin = (
    category_profit / category_sales
) * 100
category_average_sales = np.mean(
    sales_data,
    axis=0
)
category_units_sold = np.sum(
    units_sold,
    axis=0
)
# EXPANSION RECOMMENDATION
expansion_condition = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_profit_margin > 25)
)
eligible_stores = stores[
    expansion_condition
]
# MARKETING RECOMMENDATION
marketing_condition = (
    (category_average_sales < 300000) &
    (category_profit_margin > 25)
)
marketing_categories = categories[
    marketing_condition
]
# COST OPTIMIZATION
cost_condition = (
    (cost_data > 250000) &
    (profit_margin < 25)
)
cost_rows, cost_cols = np.where(
    cost_condition
)
# INVENTORY REORDER
closing_stock = opening_stock - units_sold
reorder_condition = closing_stock < 25
reorder_quantity = np.where(
    reorder_condition,
    100 - closing_stock,
    0
)
reorder_rows, reorder_cols = np.where(
    reorder_condition
)
# BEST / LOWEST STORE
best_store_index = np.argmax(
    store_profit
)
lowest_store_index = np.argmin(
    store_profit
)
# BEST / LOWEST CATEGORY
best_category_index = np.argmax(
    category_profit
)
lowest_category_index = np.argmin(
    category_profit
)
# PRINT REPORT
print("SMARTMART RETAIL PERFORMANCE REPORT")
# COMPANY SUMMARY
print("\n## COMPANY SUMMARY")
print()
print("Total Sales:", total_sales)
print("Total Cost:", total_cost)
print("Total Profit:", total_profit)
print( "Overall Profit Margin:",round(overall_profit_margin, 2),"%")
print("Average Transaction Value:",round(average_transaction, 2))
print( "Highest Individual Sales:",highest_sales)
print("Lowest Individual Sales:",lowest_sales)
# BEST-PERFORMING STORE
print("\n## BEST-PERFORMING STORE")
print()
print("Store:",stores[best_store_index])
print("Sales:",store_sales[best_store_index])
print("Cost:",store_cost[best_store_index])
print("Profit:",store_profit[best_store_index])
print("Profit Margin:",round(store_profit_margin[best_store_index],2), "%")
# MOST PROFITABLE CATEGORY
print("\n## MOST PROFITABLE CATEGORY")
print()
print("Category:",categories[best_category_index])
print("Sales:",category_sales[best_category_index])
print("Cost:",category_cost[best_category_index])
print("Profit:",category_profit[best_category_index])
print("Profit Margin:",round(category_profit_margin[best_category_index],2),"%")

# EXPANSION RECOMMENDATIONS
print("\n## EXPANSION RECOMMENDATIONS")
print()
print("Eligible Stores:",eligible_stores)
# COST OPTIMIZATION
print("\n## COST OPTIMIZATION")
print()
if len(cost_rows) == 0:
    print("No combinations require cost optimization.")
else:
    for i in range(len(cost_rows)):
        r = cost_rows[i]
        c = cost_cols[i]
        print("Store:",stores[r])
        print("Category:",categories[c])
        print("Cost:",cost_data[r, c])
        print("Profit Margin:", round(profit_margin[r, c],2),"%")
        print()
# INVENTORY REORDER
print("\n## INVENTORY REORDER")
print()
if len(reorder_rows) == 0:
    print("No inventory reorder required.")
else:
    for i in range(len(reorder_rows)):
        r = reorder_rows[i]
        c = reorder_cols[i]
        print("Store:",stores[r])
        print("Category:",categories[c])
        print("Closing Stock:",closing_stock[r, c])
        print("Reorder Quantity:",reorder_quantity[r, c])
        print()
# ADDITIONAL MANAGEMENT RECOMMENDATIONS
print("\n## LOWEST-PERFORMING STORE")
print()
print("Store:",stores[lowest_store_index])
print("Profit:",store_profit[lowest_store_index])
print("\n## LOWEST-PROFIT CATEGORY")
print()
print("Category:",categories[lowest_category_index])
print("Profit:",category_profit[lowest_category_index])
print("\n## CATEGORY REQUIRING ADDITIONAL MARKETING")
print()
print("Categories:",marketing_categories)

SMARTMART RETAIL PERFORMANCE REPORT

## COMPANY SUMMARY

Total Sales: 11675000
Total Cost: 8600000
Total Profit: 3075000
Overall Profit Margin: 26.34 %
Average Transaction Value: 389166.67
Highest Individual Sales: 1050000
Lowest Individual Sales: 175000

## BEST-PERFORMING STORE

Store: Mumbai
Sales: 2820000
Cost: 2065000
Profit: 755000
Profit Margin: 26.77 %

## MOST PROFITABLE CATEGORY

Category: Electronics
Sales: 4290000
Cost: 3250000
Profit: 1040000
Profit Margin: 24.24 %

## EXPANSION RECOMMENDATIONS

Eligible Stores: ['Mumbai']

## COST OPTIMIZATION

Store: Bengaluru
Category: Electronics
Cost: 640000
Profit Margin: 24.71 %

Store: Hyderabad
Category: Electronics
Cost: 590000
Profit Margin: 24.36 %

Store: Hyderabad
Category: Groceries
Cost: 350000
Profit Margin: 23.91 %

Store: Chennai
Category: Electronics
Cost: 700000
Profit Margin: 23.91 %

Store: Chennai
Category: Groceries
Cost: 295000
Profit Margin: 24.36 %

Store: Mumbai
Category: Electronics
Cost: 790000
Profit Margin: